language: php

php:
- 5.4

env:
  global:
  - secure: "eG/9gTA9uK5g5r2sCsvRheKMlJcDhdBNjqVi/xnvAHFaFWl/wsbO7ZCQkiCO\n2PZ0EvQi1FglumvEAfiQOaR/zygSAbgsqnekdSY/JGulWwBCApHrjzzR/KH9\nKF/89YyZfkcxRoZSyYFMg01ELuymNV9gfCMFzpI94Q/eV+STusg="
  - secure: "BzHrWDBL1pFDN+H15kSHEXVLp88Qqa1bBbAjyJMYlsTJG3OIHAJG9Etfo3Do\nlXTnO0ZGg3GtO2USUbliAyEOFiEgKfIXzFuyu/DzoxXkG2oSiMBKqu+OWE66\nMqOyPbq6sCfqNgb3FoopiRBohuEaGm0vX2ufWfVLDohpchxMLGo="

install:
  - sudo add-apt-repository ppa:nginx/stable -y
  - sudo apt-get update
  - sudo apt-get install nginx

before_script:
- chmod +x ./build/before_script.sh
- chmod +x ./build/sauce_connect_setup.sh
- sh -c ./build/before_script.sh
- sh -c ./build/sauce_connect_setup.sh

script:
- sh -c ./build/script.sh

notifications:
  email: false
