language: php

php:
- 5.4

env:
  global:
  - secure: "eG/9gTA9uK5g5r2sCsvRheKMlJcDhdBNjqVi/xnvAHFaFWl/wsbO7ZCQkiCO\n2PZ0EvQi1FglumvEAfiQOaR/zygSAbgsqnekdSY/JGulWwBCApHrjzzR/KH9\nKF/89YyZfkcxRoZSyYFMg01ELuymNV9gfCMFzpI94Q/eV+STusg="
  - secure: "WSAGTnjjqafUGJEnrd2UqV+EEXzgdV1DqLLdD4CisvnMNXsI0IAw6RaY6jz0\nJTJ6mouDhdfN1pT+JT8KmM28VbzdQjSbBEqGHmCnGJ7Rp128IEY/PMz7O8hm\nfXUetf+POvPkhWmRETrrtbdwyQL3MxNDG4792y7SK482RZnYt9M="

install:
  - sudo add-apt-repository ppa:nginx/stable -y
  - sudo apt-get update
  - sudo apt-get install nginx

before_script:
- chmod +x ./build/before_script.sh
- chmod +x ./build/sauce_connect_setup.sh
- sh -c ./build/before_script.sh
- sh -c ./build/sauce_connect_setup.sh

script:
- sh -c ./build/script.sh

notifications:
  email: false
